project:
  type: website
  output-dir: docs

website:
  title: "quartoCourseBlog"
  navbar:
    right:
      - about.qmd
      links:
    - icon: instagram
      text: instagram
      href: https://www.instagram.com/salem.csp5/
    - icon: facebook
      text: facebook
      href: https://www.facebook.com/profile.php?id=61590308556408
format:
  html:
    theme: minty
    css: styles.css

editor: visual

