project:
  type: website
  output-dir: docs

website:
  title: "Salem"
  navbar:
    right:
      - about.qmd
      - icon: instagram
        href: https://www.instagram.com/salem.csp5/
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61590308556408
format:
  html:
    theme: minty
    css: styles.css

editor: visual

